version: '3.1'
services:
  # Matomo - Web Analytics
  matomo:
    image: matomo
    env_file:
      - .env
      - .env.dev
    container_name: matomo_01
    ports:
      - ${FORWARDED_PORT_MATOMO}:80
    volumes:
      - ./matomo_data:/var/www/html
    networks:
      - mysql

  # MySQL - Database for Matomo
  mysql:
    image: mysql:8.4.4
    container_name: mysql_01
    restart: always
    env_file:
      - .env
      - .env.dev
    ports:
      - ${FORWARDED_PORT_MYSQL}:3306
    volumes: 
      - ./mysql_data:/var/lib/mysql  # Cambiado para persistencia
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mysql

  # phpMyAdmin - Database Management
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_01
    restart: always
    env_file:
      - .env
      - .env.dev
    ports:
      - ${FORWARDED_PORT_PGADMIN}:80
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
